-- DROP DATABASE
-- DROP DATABASE IF EXISTS example_db;

-- CREATE DATABASE 
CREATE DATABASE IF NOT EXISTS example_db;

-- CREATE USER TABLE
CREATE Table users(
    id INT PRIMARY KEY AUTO_INCREMENT
    firstName VARCHAR(50) NOT NULL
    firstName VARCHAR(50) NOT NULL
    username VARCHAR(50) UNIQUE NOT NULL
    email VARCHAR(100) UNIQUE NOT NULL
    created DATETIME
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
)

-- CREATE PRODUCT TABLE

CREATE Table product(
    id INT PRIMARY KEY AUTO_INCREMENT,
    productName VARCHAR(50),
    experience VARCHAR(50),
    created DATETIME
)